# Generated by Django 4.0 on 2021-12-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Super_AdminAccount',
            fields=[
                ('SId', models.AutoField(primary_key=True, serialize=False)),
                ('Fname', models.CharField(default='', max_length=255)),
                ('Lname', models.CharField(default='', max_length=255)),
                ('Email', models.EmailField(default='', max_length=255)),
                ('Username', models.CharField(default='', max_length=255)),
                ('Password', models.TextField(default='', max_length=3000)),
                ('ContactNo', models.CharField(default='', max_length=100)),
                ('Role', models.CharField(choices=[('superadmin', 'superadmin'), ('subadmin', 'subadmin')], default='subadmin', max_length=10)),
                ('Profile', models.ImageField(default='SuperAdmin/dummy.jpg', upload_to='SuperAdmin/')),
            ],
        ),
    ]
