# Generated by Django 4.0.3 on 2022-04-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmodel',
            name='ogp',
            field=models.CharField(blank=True, help_text='ogp for meta description', max_length=255, null=True, verbose_name='ogp Description'),
        ),
    ]
