# Generated by Django 4.0.3 on 2022-07-16 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couse_topic', to='webapi.category'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(default='SuperAdmin/dummy.svg', upload_to='Users/'),
        ),
    ]
