# Generated by Django 4.0.3 on 2022-03-18 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(default='', max_length=255)),
                ('lname', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(default='', max_length=255)),
                ('username', models.CharField(default='', max_length=255)),
                ('password', models.TextField(default='')),
                ('profile', models.ImageField(default='SuperAdmin/dummy.jpg', upload_to='SuperAdmin/')),
            ],
        ),
        migrations.DeleteModel(
            name='Super_AdminAccount',
        ),
    ]
