# Generated by Django 3.2.5 on 2022-07-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0002_alter_reviewmodel_categories_alter_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='fileBridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(default='', upload_to='exportfiles/')),
            ],
        ),
        migrations.AlterField(
            model_name='recentlyviewcontent',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
