# Generated by Django 3.2.5 on 2022-08-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0002_auto_20220804_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmodel',
            name='slug',
            field=models.SlugField(blank=True, help_text='slug is an Unique value for singel categories page URL, Same as category Name'),
        ),
    ]
