# Generated by Django 4.0.3 on 2022-04-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0002_remove_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('normaluser', 'normaluser'), ('editor', 'editor')], default='normaluser', max_length=20),
        ),
    ]
