# Generated by Django 4.0.3 on 2022-04-05 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0002_reviewmodel_ogp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='meta_description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='ogp',
            field=models.TextField(default=''),
        ),
    ]
