# Generated by Django 3.2.5 on 2022-08-10 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0003_reviewmodel_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewmodel',
            old_name='slug',
            new_name='postslug',
        ),
    ]
