# Generated by Django 4.0.3 on 2022-03-18 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0003_membershipplan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MembershipPlan',
        ),
    ]
