# Generated by Django 3.2.5 on 2022-07-27 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0003_auto_20220723_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapi.user'),
        ),
        migrations.AlterField(
            model_name='recentlyviewcontent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
