# Generated by Django 4.0.3 on 2022-03-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0004_delete_membershipplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(default='SuperAdmin/dummy.jpg', upload_to='Users/'),
        ),
    ]
