# Generated by Django 4.0.3 on 2022-04-06 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0004_rename_ogp_reviewmodel_ogp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewmodel',
            name='tags',
        ),
        migrations.AddField(
            model_name='reviewmodel',
            name='tags',
            field=models.TextField(default=''),
        ),
    ]
