# Generated by Django 4.0.3 on 2022-03-22 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0007_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
