# Generated by Django 4.0.3 on 2022-04-06 02:06

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
        ('webapi', '0007_reviewmodel_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewmodel',
            name='tags',
        ),
        migrations.AddField(
            model_name='reviewmodel',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
