# Generated by Django 4.0.3 on 2022-04-06 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0008_remove_reviewmodel_tags_reviewmodel_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewmodel',
            name='tags',
        ),
    ]
