# Generated by Django 4.0.3 on 2022-03-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0010_reviewmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='CategoryType',
            field=models.CharField(default='', max_length=20),
        ),
    ]
