# Generated by Django 4.0.3 on 2022-03-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0011_category_categorytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
