# Generated by Django 4.0.3 on 2022-05-10 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0011_recentlyviewcourse_recentlyviewcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('comment', models.TextField(default='')),
                ('ratingStatus', models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', max_length=20)),
                ('commentstatus', models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', max_length=20)),
                ('course_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapi.category')),
            ],
        ),
        migrations.CreateModel(
            name='ContentRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('comment', models.TextField(default='')),
                ('ratingStatus', models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', max_length=20)),
                ('commentstatus', models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', max_length=20)),
                ('content_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapi.reviewmodel')),
            ],
        ),
    ]
