# Generated by Django 4.0.3 on 2022-05-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0012_courserating_contentrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentrating',
            name='comment',
            field=models.FloatField(default=''),
        ),
        migrations.AlterField(
            model_name='courserating',
            name='comment',
            field=models.FloatField(default=''),
        ),
    ]
