# Generated by Django 4.0.3 on 2022-05-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0013_alter_contentrating_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentrating',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='courserating',
            name='comment',
            field=models.TextField(default=''),
        ),
    ]
