# Generated by Django 4.0.3 on 2022-05-10 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0014_alter_contentrating_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentrating',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapi.user'),
        ),
        migrations.AddField(
            model_name='courserating',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapi.user'),
        ),
    ]
