# Generated by Django 4.0.3 on 2022-05-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0016_coursepriority'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Otp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='OtpCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='OtpStatus',
            field=models.CharField(default='False', max_length=10),
        ),
    ]
