# Generated by Django 4.0.3 on 2022-06-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0020_blacklisttoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Type',
            field=models.CharField(choices=[('popularcourses', 'popularcourses'), ('categoryA', 'categoryA'), ('categoryB', 'categoryB'), ('categoryC', 'categoryC'), ('categoryD', 'categoryD')], default='popularcourses', max_length=30),
        ),
    ]
