# Generated by Django 4.0.3 on 2022-06-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0022_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Otp',
            field=models.BigIntegerField(default=0),
        ),
    ]
