# Generated by Django 4.0.3 on 2022-06-15 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0023_alter_user_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepriority',
            name='PriorityType',
            field=models.CharField(default='', max_length=255),
        ),
    ]
