# Generated by Django 4.0.3 on 2022-06-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0025_bookmarkname'),
    ]

    operations = [
        migrations.CreateModel(
            name='parentCategory',
            fields=[
                ('parentid', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='slug is an Unique value for singel categories page URL, Same as category Name', unique=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='category_pic')),
                ('unique_identifier', models.BigIntegerField(blank=True, help_text="You don't have to do it manually, & After you save it you can also edit", null=True, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Course_or_Chapter'},
        ),
    ]
