# Generated by Django 4.0.3 on 2022-06-18 07:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0026_parentcategory_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parentcategory',
            options={'verbose_name': 'Category'},
        ),
        migrations.AlterField(
            model_name='parentcategory',
            name='parentid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
