# Generated by Django 4.0.3 on 2022-06-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0027_alter_parentcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='parentcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
