const EditCourseStructureData = [
  {
    title: "Git & GitHub Introduction",
    name: "Git & GitHub Introduction",
    unique_idetifier: 4720941,
    image: "http://localhost:3000/editcoursestructure",
    createddate: "Nov,10 2010",
    updateddate: "Nov, 10 2010",
  },
  {
    title: "Git & GitHub Introduction",
    name: "Git & GitHub Introduction",
    unique_idetifier: 4720941,
    image: "http://localhost:3000/editcoursestructure",
    createddate: "Nov,10 2010",
    updateddate: "Nov, 10 2010",
  },
  {
    title: "Git & GitHub Introduction",
    name: "Git & GitHub Introduction",
    unique_idetifier: 4720941,
    image: "http://localhost:3000/editcoursestructure",
    createddate: "Nov,10 2010",
    updateddate: "Nov, 10 2010",
  },
  {
    title: "Git & GitHub Introduction",
    name: "Git & GitHub Introduction",
    unique_idetifier: 4720941,
    image: "http://localhost:3000/editcoursestructure",
    createddate: "Nov,10 2010",
    updateddate: "Nov, 10 2010",
  },
  {
    title: "Git & GitHub Introduction",
    name: "Git & GitHub Introduction",
    unique_idetifier: 4720941,
    image: "http://localhost:3000/editcoursestructure",
    createddate: "Nov,10 2010",
    updateddate: "Nov, 10 2010",
  },
  {
    title: "Git & GitHub Introduction",
    name: "Git & GitHub Introduction",
    unique_idetifier: 4720941,
    image: "http://localhost:3000/editcoursestructure",
    createddate: "Nov,10 2010",
    updateddate: "Nov, 10 2010",
  },
  {
    title: "Git & GitHub Introduction",
    name: "Git & GitHub Introduction",
    unique_idetifier: 4720941,
    image: "http://localhost:3000/editcoursestructure",
    createddate: "Nov,10 2010",
    updateddate: "Nov, 10 2010",
  },
  {
    title: "Git & GitHub Introduction",
    name: "Git & GitHub Introduction",
    unique_idetifier: 4720941,
    image: "http://localhost:3000/editcoursestructure",
    createddate: "Nov,10 2010",
    updateddate: "Nov, 10 2010",
  },
  {
    title: "Git & GitHub Introduction",
    name: "Git & GitHub Introduction",
    unique_idetifier: 4720941,
    image: "http://localhost:3000/editcoursestructure",
    createddate: "Nov,10 2010",
    updateddate: "Nov, 10 2010",
  },
  {
    title: "Git & GitHub Introduction",
    name: "Git & GitHub Introduction",
    unique_idetifier: 4720941,
    image: "http://localhost:3000/editcoursestructure",
    createddate: "Nov,10 2010",
    updateddate: "Nov, 10 2010",
  },
];

export default EditCourseStructureData;
